/**
 * VB6 Interpreter Hook
 * 
 * React hook for running the VB6 interpreter with vehicle inputs
 */

import { useState, useCallback } from 'react';
import { VB6Interpreter, VB6Inputs, VB6Outputs } from './vb6Interpreter';
import type { Vehicle } from '../../schemas/vehicle.schema';

// Simple weather interface for VB6 interpreter
interface VB6Weather {
  temperature: number;
  barometer: number;
  humidity: number;
  elevation: number;
  trackTemp: number;
  windSpeed?: number;
  windDirection?: number;
}

// Cache for the loaded TIMESLIP.FRM source
let timeslipSourceCache: string | null = null;

/**
 * Load the TIMESLIP.FRM source file
 */
async function loadTimeslipSource(): Promise<string> {
  if (timeslipSourceCache) {
    return timeslipSourceCache;
  }
  
  const response = await fetch('/vb6/TIMESLIP.FRM');
  if (!response.ok) {
    throw new Error(`Failed to load TIMESLIP.FRM: ${response.status}`);
  }
  
  timeslipSourceCache = await response.text();
  return timeslipSourceCache;
}

// Map fuel system string to VB6 numeric code
function fuelSystemToCode(fuelSystem?: string): number {
  const map: Record<string, number> = {
    'Gas+Carb': 1,
    'Gas+FI': 2,
    'Alcohol+Carb': 3,
    'Alcohol+FI': 4,
    'Nitro+FI': 5,
    'Gas+Turbo': 6,
    'Alcohol+Turbo': 7,
    'Nitro+Turbo': 8,
    'Diesel': 9,
  };
  return map[fuelSystem ?? ''] ?? 1;
}

/**
 * Convert RSA Vehicle to VB6 Inputs
 */
function vehicleToVB6Inputs(vehicle: Vehicle, weather: VB6Weather): VB6Inputs {
  // Extract gear ratios and efficiencies from arrays
  const gearRatios = vehicle.gearRatios ?? [2.5, 1.8, 1.4, 1.0, 0, 0];
  const gearEffs = vehicle.gearEfficiencies ?? [0.95, 0.97, 0.97, 0.97, 0.97, 0.97];
  const shiftRpms = vehicle.shiftRPMs ?? [6000, 6000, 6000, 6000, 0, 0];
  
  // Ensure arrays have 6 elements
  while (gearRatios.length < 6) gearRatios.push(0);
  while (gearEffs.length < 6) gearEffs.push(0.97);
  while (shiftRpms.length < 6) shiftRpms.push(0);
  
  return {
    // Vehicle
    Weight: vehicle.weightLb,
    TireDia: vehicle.tireDiaIn,
    TireWidth: vehicle.tireWidthIn ?? 10,
    GearRatio: vehicle.rearGear,
    Wheelbase: vehicle.wheelbaseIn ?? 110,
    Rollout: vehicle.rolloutIn,
    Overhang: vehicle.overhangIn ?? 36,
    StaticFWt: vehicle.staticFrontWeightLb ? (vehicle.staticFrontWeightLb / vehicle.weightLb * 100) : 52,
    YCG: vehicle.cgHeightIn ?? 18,
    BodyStyle: vehicle.bodyStyle ?? 1,
    
    // Engine
    PeakHP: vehicle.powerHP,
    RPMPeakHP: vehicle.rpmAtPeakHP ?? 5500,
    Displacement: vehicle.displacementCID ?? 350,
    FuelSystem: fuelSystemToCode(vehicle.fuelSystem),
    HPTQMult: vehicle.hpTorqueMultiplier ?? 1.0,
    EnginePMI: vehicle.enginePMI ?? 0.3,
    
    // Transmission
    TransType: vehicle.transmissionType === 'converter' ? 1 : 0,
    TransGR: gearRatios,
    TransEff: gearEffs,
    ShiftRPM: shiftRpms,
    TorqueMult: vehicle.converterTorqueMult ?? 2.0,
    Slippage: vehicle.clutchSlippage ?? vehicle.converterSlippage ?? 0,
    SlipStallRPM: vehicle.clutchSlipRPM ?? vehicle.converterStallRPM ?? 2500,
    ConvDia: vehicle.converterDiameterIn ?? 11,
    LockUp: vehicle.converterLockup ? 1 : 0,
    TransPMI: vehicle.transPMI ?? 0.1,
    TiresPMI: vehicle.tiresPMI ?? 0.5,
    
    // Aerodynamics
    RefArea: vehicle.frontalAreaFt2 ?? 24,
    DragCoef: vehicle.cd ?? 0.45,
    LiftCoef: vehicle.liftCoeff ?? 0,
    
    // Environment
    WindSpeed: weather.windSpeed ?? 0,
    WindAngle: weather.windDirection ?? 0,
    TractionIndex: 1.0,
    Efficiency: vehicle.transEfficiency ?? 0.85,
    
    // HP Curve (generated by ENGINE sub if empty)
    EngineRPM: [],
    EngineHP: [],
    EngineTQ: [],
  };
}

interface UseVB6InterpreterResult {
  loading: boolean;
  error: string | null;
  outputs: VB6Outputs | null;
  runSimulation: (vehicle: Vehicle, weather: VB6Weather) => Promise<VB6Outputs>;
}

/**
 * React hook for running the VB6 interpreter
 */
export function useVB6Interpreter(): UseVB6InterpreterResult {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [outputs, setOutputs] = useState<VB6Outputs | null>(null);
  
  const runSimulation = useCallback(async (vehicle: Vehicle, weather: VB6Weather): Promise<VB6Outputs> => {
    setLoading(true);
    setError(null);
    
    try {
      console.log('[useVB6Interpreter] Loading TIMESLIP.FRM...');
      const source = await loadTimeslipSource();
      console.log(`[useVB6Interpreter] Loaded ${source.length} bytes`);
      
      console.log('[useVB6Interpreter] Creating interpreter...');
      const interpreter = new VB6Interpreter(source);
      
      console.log('[useVB6Interpreter] Setting inputs...');
      const inputs = vehicleToVB6Inputs(vehicle, weather);
      interpreter.setInputs(inputs);
      
      // Set weather form controls
      const fc = (interpreter as unknown as { state: { formControls: Map<string, number> } }).state.formControls;
      fc.set('gc_temperature', weather.temperature ?? 70);
      fc.set('gc_barometer', weather.barometer ?? 29.92);
      fc.set('gc_humidity', weather.humidity ?? 50);
      fc.set('gc_elevation', weather.elevation ?? 0);
      fc.set('gc_tracktemp', weather.trackTemp ?? 100);
      
      console.log('[useVB6Interpreter] Running simulation...');
      const startTime = performance.now();
      const result = interpreter.run();
      const endTime = performance.now();
      
      console.log(`[useVB6Interpreter] Completed in ${(endTime - startTime).toFixed(1)}ms`);
      console.log(`[useVB6Interpreter] ET: ${result.ET.toFixed(3)}s @ ${result.MPH.toFixed(1)} mph`);
      
      setOutputs(result);
      return result;
      
    } catch (err) {
      const message = err instanceof Error ? err.message : String(err);
      console.error('[useVB6Interpreter] Error:', message);
      setError(message);
      throw err;
    } finally {
      setLoading(false);
    }
  }, []);
  
  return { loading, error, outputs, runSimulation };
}

/**
 * Direct function to run VB6 interpreter (non-React)
 */
export async function runVB6Simulation(vehicle: Vehicle, weather: VB6Weather): Promise<VB6Outputs> {
  const source = await loadTimeslipSource();
  const interpreter = new VB6Interpreter(source);
  
  const inputs = vehicleToVB6Inputs(vehicle, weather);
  interpreter.setInputs(inputs);
  
  // Set weather form controls
  const fc = (interpreter as unknown as { state: { formControls: Map<string, number> } }).state.formControls;
  fc.set('gc_temperature', weather.temperature ?? 70);
  fc.set('gc_barometer', weather.barometer ?? 29.92);
  fc.set('gc_humidity', weather.humidity ?? 50);
  fc.set('gc_elevation', weather.elevation ?? 0);
  fc.set('gc_tracktemp', weather.trackTemp ?? 100);
  
  return interpreter.run();
}

export { loadTimeslipSource, vehicleToVB6Inputs };
export type { VB6Weather };
