/**
 * VB6 Interpreter Test
 * 
 * Test harness for running the VB6 interpreter with MOTORCYC inputs
 * to verify we get the expected ET of 11.99s
 */

import { VB6Interpreter, VB6Inputs } from './vb6Interpreter';

// MOTORCYC test case inputs (from the original VB6 program)
const MOTORCYC_INPUTS: VB6Inputs = {
  // Vehicle
  Weight: 650,           // lbs (bike + rider)
  TireDia: 26.3,         // inches
  TireWidth: 7.1,        // inches
  GearRatio: 2.94,       // final drive ratio
  Wheelbase: 58,         // inches
  Rollout: 12,           // inches
  Overhang: 20,          // inches (front overhang)
  StaticFWt: 47,         // % static front weight
  YCG: 22,               // inches (CG height)
  BodyStyle: 8,          // 8 = motorcycle
  
  // Engine
  PeakHP: 195,           // HP
  RPMPeakHP: 10500,      // RPM at peak HP
  Displacement: 1000,    // cc
  FuelSystem: 2,         // 2 = fuel injection
  HPTQMult: 1.0,         // HP/TQ multiplier
  EnginePMI: 0.15,       // Engine polar moment of inertia
  
  // Transmission
  TransType: 0,          // 0 = clutch (not converter)
  TransGR: [2.615, 2.0, 1.666, 1.444, 1.304, 1.208], // Gear ratios 1-6
  TransEff: [0.95, 0.97, 0.97, 0.97, 0.97, 0.97],    // Gear efficiencies 1-6
  ShiftRPM: [10500, 10500, 10500, 10500, 10500, 0],  // Shift RPMs 1-6
  TorqueMult: 1.0,       // Torque multiplier (for converter)
  Slippage: 0,           // Clutch slippage
  SlipStallRPM: 10000,   // Slip RPM (clutch) or Stall RPM (converter)
  ConvDia: 0,            // Converter diameter (not used for clutch)
  LockUp: 0,             // Lockup RPM (for converter)
  TransPMI: 0.05,        // Transmission PMI
  TiresPMI: 0.3,         // Tires PMI
  
  // Aerodynamics
  RefArea: 6,            // sq ft (frontal area)
  DragCoef: 0.65,        // Drag coefficient
  LiftCoef: 0,           // Lift coefficient
  
  // Environment
  WindSpeed: 0,          // mph
  WindAngle: 0,          // degrees
  TractionIndex: 1.0,    // Traction index
  Efficiency: 0.95,      // Overall efficiency
  
  // HP Curve (Quarter Jr generates this from peak HP)
  EngineRPM: [],         // Generated by ENGINE sub
  EngineHP: [],          // Generated by ENGINE sub
  EngineTQ: [],          // Generated by ENGINE sub
};

// Weather conditions (standard)
const WEATHER = {
  Temperature: 70,       // °F
  Barometer: 29.92,      // inHg
  Humidity: 50,          // %
  Elevation: 0,          // ft
  TrackTemp: 100,        // °F
};

/**
 * Load the TIMESLIP.FRM source file
 */
async function loadTimeslipSource(): Promise<string> {
  // In a browser context, we'd fetch this file
  // For Node.js testing, we can read it directly
  const path = 'C:/Racing Systems Analysis/RSA/Reference Files/OtherRefFiles/QPro Family 1_18_2023/QCommon/TIMESLIP.FRM';
  
  // Try fetch first (browser)
  try {
    const response = await fetch(path);
    if (response.ok) {
      return response.text();
    }
  } catch {
    // Not in browser, try Node.js fs
  }
  
  // For Node.js, we'd use fs.readFileSync
  // Since we're in a browser context, throw an error
  throw new Error('Cannot load TIMESLIP.FRM - please ensure the file is accessible');
}

/**
 * Run the VB6 interpreter with MOTORCYC inputs
 */
export async function runMotorcycTest(): Promise<void> {
  console.log('='.repeat(60));
  console.log('VB6 Interpreter Test - MOTORCYC');
  console.log('='.repeat(60));
  console.log('Expected ET: 11.99s');
  console.log('');
  
  try {
    const source = await loadTimeslipSource();
    console.log(`Loaded TIMESLIP.FRM (${source.length} bytes)`);
    
    const interpreter = new VB6Interpreter(source);
    
    // Set inputs
    interpreter.setInputs(MOTORCYC_INPUTS);
    
    // Set weather controls
    const fc = (interpreter as unknown as { state: { formControls: Map<string, number> } }).state.formControls;
    fc.set('gc_temperature', WEATHER.Temperature);
    fc.set('gc_barometer', WEATHER.Barometer);
    fc.set('gc_humidity', WEATHER.Humidity);
    fc.set('gc_elevation', WEATHER.Elevation);
    fc.set('gc_tracktemp', WEATHER.TrackTemp);
    
    console.log('Running simulation...');
    const startTime = performance.now();
    
    const outputs = interpreter.run();
    
    const endTime = performance.now();
    console.log(`Execution time: ${(endTime - startTime).toFixed(2)}ms`);
    console.log('');
    
    console.log('='.repeat(60));
    console.log('RESULTS');
    console.log('='.repeat(60));
    console.log(`60ft:    ${outputs.time60ft.toFixed(3)}s`);
    console.log(`330ft:   ${outputs.time330ft.toFixed(3)}s`);
    console.log(`660ft:   ${outputs.time660ft.toFixed(3)}s @ ${outputs.mph660ft.toFixed(1)} mph`);
    console.log(`1000ft:  ${outputs.time1000ft.toFixed(3)}s`);
    console.log(`1/4mi:   ${outputs.ET.toFixed(3)}s @ ${outputs.MPH.toFixed(1)} mph`);
    console.log('');
    
    const etDiff = Math.abs(outputs.ET - 11.99);
    if (etDiff < 0.01) {
      console.log('✓ SUCCESS: ET matches VB6 target (11.99s)!');
    } else {
      console.log(`✗ MISMATCH: ET differs from target by ${etDiff.toFixed(3)}s`);
    }
    
  } catch (error) {
    console.error('Error running test:', error);
  }
}

// Export for use in browser console or test runner
export { MOTORCYC_INPUTS, WEATHER };
